-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.MAX_CLIENT_STATES = 20

NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 4
NDefines.NAI.PEACE_HIGH_WAR_EXHAUSTION_FACTOR = 8
NDefines.NAI.PEACE_DESPERATION_FACTOR = 100
NDefines.NAI.PEACE_WAR_EXHAUSTION_FACTOR = 5
NDefines.NAI.PEACE_WAR_DIRECTION_FACTOR = 3
NDefines.NAI.BORDER_DISTANCE_SCORE_IMPACT = 10
NDefines.NAI.IMPORANT_PROVINCE_THRESHOLD = 0.01

NDefines.NMilitary.SUPPLYLI_ATTRITION = 2
NDefines.NMilitary.LEADER_MIN_PIPS = 1
NDefines.NMilitary.ARMY_DRILL_MAX_MORALE = 1
NDefines.NMilitary.ARMY_DRILL_SKILL_MONTHS = 48
NDefines.NMilitary.RIVER_CROSSING_PENALTY = 2
NDefines.NMilitary.STRAIT_CROSSING_PENALTY = 3
NDefines.NMilitary.SEA_LANDING_PENALTY = 4
NDefines.NMilitary.WAR_LENGTH_DAMAGE_MODIFIER = 0.07
NDefines.NMilitary.CANNOT_RETREAT_DAYS = 8
NDefines.NCountry.PS_ARTILLERY_BARRAGE = 25
NDefines.NCountry.PS_NAVAL_BARRAGE = 25
NDefines.NMilitary.REGULAR_LEADER_POWER = 2
NDefines.NMilitary.DAYS_PER_SIEGE_PHASE = 20


