NDefines.NCountry.ALLOW_FEMALE_GENERALS = 1
NDefines.NCountry.FEMALE_ADVISOR_CHANCE = 25
NDefines.NCountry.ABANDON_IDEAGROUP_REFUND = 0.8
NDefines.NCountry.POWER_MAX = 5000
NDefines.NCountry.PS_ARTILLERY_BARRAGE = 25
NDefines.NCountry.PS_NAVAL_BARRAGE = 25
NDefines.NCountry.MAX_EXTRA_PERSONALITIES = 4
NDefines.NCountry.YEARS_PER_EXTRA_PERSONALITY = 10

NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 4
NDefines.NDiplomacy.COUNTERESPIONAGE_DISCOVER_CHANCE = 0.75
NDefines.NDiplomacy.WAR_REPARATIONS_FACTOR = 0.25

NDefines.NAI.PEACE_HIGH_WAR_EXHAUSTION_FACTOR = 8
NDefines.NAI.PEACE_DESPERATION_FACTOR = 100
NDefines.NAI.PEACE_WAR_EXHAUSTION_FACTOR = 5
NDefines.NAI.PEACE_WAR_DIRECTION_FACTOR = 3
NDefines.NAI.BORDER_DISTANCE_SCORE_IMPACT = 10
NDefines.NAI.IMPORANT_PROVINCE_THRESHOLD = 0.01

NDefines.NMilitary.SUPPLYLI_ATTRITION = 2
NDefines.NMilitary.LEADER_MIN_PIPS = 1
NDefines.NMilitary.ARMY_DRILL_MAX_MORALE = 0.1
NDefines.NMilitary.ARMY_DRILL_SKILL_MONTHS = 48
NDefines.NMilitary.RIVER_CROSSING_PENALTY = 2
NDefines.NMilitary.STRAIT_CROSSING_PENALTY = 3
NDefines.NMilitary.SEA_LANDING_PENALTY = 4
NDefines.NMilitary.WAR_LENGTH_DAMAGE_MODIFIER = 0.1
NDefines.NMilitary.CANNOT_RETREAT_DAYS = 8
NDefines.NMilitary.REGULAR_LEADER_POWER = 2
NDefines.NMilitary.DAYS_PER_SIEGE_PHASE = 20
